#!/usr/bin/env node

'use strict';

const fs = require('fs');
const path = require('path');
const jsondiffpatch = require('jsondiffpatch');

const collect = require('..');

function filter(name) {
    if (process.argv.length <= 2) {
        return true;
    }

    const match = part => name.indexOf(part) >= 0;
    const negate = process.argv[2] === '!';
    const argv = process.argv.slice(negate ? 3 : 2);

    return negate ? !argv.some(match) : argv.some(match);
}

function run(name) {
    try {
        const title = path.basename(name, 'js');
        console.log(`${title}...`);

        const code = fs.readFileSync(name, 'utf8');
        const {schemas: actual} = collect(name);
        const expected = eval(code.split('// ###')[1]);

        const delta = jsondiffpatch.diff(actual, expected);

        if (delta) {
            jsondiffpatch.console.log(delta);
        }

        return !delta;
    } catch (ex) {
        console.log(ex.message);

        return false;
    }
}

function main() {
    process.chdir(__dirname);

    const runner = path.basename(__filename);

    const list = fs.readdirSync(__dirname)
        .filter(fname => fname !== runner);

    let success = true;

    for (const name of list) {
        if (!filter(name)) {
            continue;
        }

        if (fs.lstatSync(name).isDirectory()) {
            continue;
        }

        const ok = run(name);

        success = success && ok;
    }

    process.exit(success ? 0 : 1);
}

main();
