#!/usr/bin/env node

'use strict';

const fs = require('fs');
const path = require('path');
const jsondiffpatch = require('jsondiffpatch');

const collect = require('..');

const runner = path.basename(__filename);

const list = fs.readdirSync(__dirname)
    .filter(fname => fname !== runner)
    .map(fname => path.relative('.', path.join(__dirname, fname)));

function filter(fpath) {
    if (process.argv.length > 2) {
        return process.argv.slice(2).every(part => fpath.indexOf(part) >= 0);
    }

    return true;
}

for (const fpath of list) {
    if (!filter(fpath)) {
        continue;
    }

    console.log(`${fpath}...`);

    const code = fs.readFileSync(fpath, 'utf8');
    const {schemas: actual} = collect(fpath);
    const expected = eval(code.split('// ###')[1]);

    const delta = jsondiffpatch.diff(actual, expected);

    if (delta) {
        jsondiffpatch.console.log(delta);
    }
}
